### ISSUE TITLE
HMR not working with CSS variables in `:root` pseudo class

### ISSUE THREAD

**Issue by marvinhagemeister** [preactjs/wmr#509]
**Describe the bug**

```css
:root {
  --color: red; // modifiying this value doesn't trigger HMR
}

.foo {
  color: var(--color);
}
```

**To Reproduce**

**Expected behavior**

Modifying values in `:root` should lead to an HMR update

**Desktop (please complete the following information):**

- OS: [e.g. MacOS 11.2.3, Windows 10]
- Browser: [e.g. chrome, safari]
- Node Version: [e.g. 15.8]
- WMR Version: [e.g. 1.3.1]

**Additional context**
