### ISSUE TITLE
Absolute paths inside CSS not resolved against root

### ISSUE THREAD

**Issue by marvinhagemeister** [preactjs/wmr#707]
Absolute paths inside a CSS file are not resolved against `root` and miss the `?asset` search param. Repro:

```css
@font-face {
  font-family: "MyFont";
  src: url(/assets/fonts/my-font.woff2) format("woff2"),
    url(/assets/fonts/my-font.woff) format("woff");
  font-weight: 400;
}
```
